version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  shareit-server:
    build: ./server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shareit
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - postgres

  shareit-gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://server:9090
    depends_on:
      - server

volumes:
  pgdata:
